// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ArtistsInLine: typeof import('./components/ArtistsInLine.vue')['default']
    ButtonIcon: typeof import('./components/ButtonIcon.vue')['default']
    ButtonTwoTone: typeof import('./components/ButtonTwoTone.vue')['default']
    ContextMenu: typeof import('./components/ContextMenu.vue')['default']
    Cover: typeof import('./components/Cover.vue')['default']
    CoverRow: typeof import('./components/CoverRow.vue')['default']
    DailyTracksCard: typeof import('./components/DailyTracksCard.vue')['default']
    ExplicitSymbol: typeof import('./components/ExplicitSymbol.vue')['default']
    FMCard: typeof import('./components/FMCard.vue')['default']
    Modal: typeof import('./components/Modal.vue')['default']
    ModalAddTrackToPlaylist: typeof import('./components/ModalAddTrackToPlaylist.vue')['default']
    ModalNewPlaylist: typeof import('./components/ModalNewPlaylist.vue')['default']
    MvRow: typeof import('./components/MvRow.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    Player: typeof import('./components/Player.vue')['default']
    Scrollbar: typeof import('./components/Scrollbar.vue')['default']
    Separator: typeof import('./components/Separator.vue')['default']
    Toast: typeof import('./components/Toast.vue')['default']
    TrackList: typeof import('./components/TrackList.vue')['default']
    TrackListItem: typeof import('./components/TrackListItem.vue')['default']
  }
}

export { }
